version: '3.0'
services:
  webserver:
    image: kedro-airflow:latest
    ports:
      - 8080:8080
      - 4141:4141 # kedro-viz
    # environment:
    #   - AIRFLOW_HOME=/usr/local/airflow/example
    volumes:
      - ./example:/usr/local/airflow/example
      - ./example/airflow_dags:/usr/local/airflow/dags
    command: bash -c "airflow webserver"
