version: '3.0'
services:
  webserver:
    image: kedro-airflow:latest
    tty: true
    ports:
      - 8080:8080
    # environment:
    #   - AIRFLOW_HOME=/usr/local/airflow/example1
    volumes:
      - ./example1:/usr/local/airflow/example1
      - ./example1/airflow_dags:/usr/local/airflow/dags
    command: bash -c "kedro install && airflow webserver"